name: Format
on:
  pull_request:
    branches: master
  push:
    branches: master

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Format
        run: |
          npm ci
          npm run format

      - name: Git auto commit action
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply prettier
